spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://korea-it.cbq8s4kiuznx.ap-northeast-2.rds.amazonaws.com:3306/todo_db
    username: admin
    password: 1q2w3e4r!!